### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by nasko222** [JMRante/Shuffle-Company#1]
Hey, sorry for writing this here. I am not sure where else but can we get in contact on PCPuzzle? I am from there. I sent a PM there

(Feel free to delete the issue)

**Comment by JMRante** [comment]
For sure, I changed my email on there a week ago and I am currently waiting for my account to be reactivated with that change (in the meantime, they deactivate your account). Once that happens I'll message you back.

**Comment by nasko222** [comment]
Unfortunately, Patrick isn't really active, so there isn't good chance that will happen soon. The deactivating is weird indeed. My second account still isn't activated (It's been 4 months).

Do you have Discord or Twitter?

**Comment by JMRante** [comment]
Ah, didn't know I needed the main admin to unlock, was hoping one of the people he delegated mod privileges to could handle it. You can find me on Discord, JMRante is my handle there too.

**Comment by nasko222** [comment]
I Need the tag to be able to find you, (Hashtag and 4 numbers)

**Comment by JMRante** [comment]
-deleted-
